# Root-level key-value pairs
GEMINI_API_KEY = "AQ.Ab8RN6JWJ7e-odM_t_rK6l1kKakmtLZ_eetcKJMZ2pRt-htjmQ"
SUPABASE_URL = "https://tukccagwkyvbyvkvkeov.supabase.co"
SUPABASE_KEY = "sb_publishable_KyZGpMeSxfjBWqvA0sPHYw_8IEUuuwJ"
# Grouped dictionary structure
[database]
user = "admin"
password = "super_secret_password"